name: ${project.name}
version: ${project.version}
author: welfare93
website: https://github.com/Majncraft/CartDNS
main: cz.majncraft.cartDNS.CartDNS
commands:
  dest:
    aliases: [destination]
    permission: cartdns.user   
  dns:
    aliases: [cartdns]
    permission: cartdns.user   
  showmap:
    aliases: [showme]
    permission: cartdns.showme
permissions:
  cartdns.manager:
    description: Gives access to all op commands
  cartdns.user:
    description: Allows you to use dns
    default: true      
  cartdns.showme:
    description: Allows you to use dynmapshow
    default: true
